# File: .gitlab-ci.yml
variables:
  SERVICE_NAME: "prolearn-compiler"

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - prod # This pipeline stage will run on this branch alone

  image: google/cloud-sdk:latest # We'll use Google Cloud SDK for Cloud Run related commands
  script:
    - echo $GCP_SERVICE_ACCOUNT > gcloud-service-key.json # Save Google cloud contents in a temporary json file
    - gcloud auth activate-service-account --key-file gcloud-service-key.json # Activate your service account
    - gcloud auth configure-docker # Configure docker environment
    - gcloud config set project $GCP_PROJECT_ID # Set the GCP Project ID to the variable name
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$SERVICE_NAME # Run the gcloud build command to build our image
    - gcloud compute instances create $SERVICE_NAME--image gcr.io/$GCP_PROJECT_ID/$SERVICE_NAME --boot-disk-size=10GB --boot-disk-type=pd-standard --machine-type=f1-micro --region=asia-southeast2 # Run the gcloud compute instance command to host our ssh server
